
means: [[0,0], [12, 15], [15, 6], [6,7], [3, 18]]
covs: [[[2, 0.5], [0.5, 4]], [[5, -2], [-2, 7]], [[1, 0.9], [0.9, 5]],
        [[10, -7], [-7, 15]], [[5, 0.9], [0.9, 5]] ]
weights: [1/20, 3/20, 4/20, 5/20, 7/20]
train_size: 5000
test_size: 500
oracle_size: 20000
seed: 0
a_s: [0, -0.25, -0.5, -0.75, -1, -1.125, -1.25, -1.5, -1.75, -2]
Delta_mean: [[1, 0], [1, 0], [1, 0], [1, 0], [1, 0]]
g: 50000
k: 6
T: 15
N: 50000
save_path: "/OSYN/Results/"
opt_data_path: "/OSYN/Opt_data/"
delta1: 0.01
delta2: 0.2


